"""Frozen WP02 detector versions, configuration, and vocabulary."""

from __future__ import annotations

ALGORITHM_NAME = "GARG-AML"
ALGORITHM_VARIANT = "undirected-basic"
ALGORITHM_VERSION = "trailsight-garg-undirected-basic-v1"
UPSTREAM_REPOSITORY = "https://github.com/B-Deprez/GARG-AML"
UPSTREAM_COMMIT = "7ce2a1dfd8c8face4e870ab67fef95afffcb068f"
UPSTREAM_CODE_PROVENANCE = f"{UPSTREAM_REPOSITORY}@{UPSTREAM_COMMIT}"

ACTIVE_SCORER = "reference-dense-v1"
COMMUNITY_ALGORITHM = "networkx-louvain"
COMMUNITY_RESOLUTION = 10.0
COMMUNITY_SEED = 1997
NETWORKX_VERSION = "3.5"
NUMPY_VERSION = "2.5.2"

IDENTITY_RULE_VERSION = "account-ref-v1"
ELIGIBILITY_RULE_VERSION = "garg-eligibility-v1"
REVIEW_BAND_POLICY_VERSION = "review-band-policy-v1"
SNAPSHOT_ID_VERSION = "detector-snapshot-v1"
ALERT_REF_VERSION = "alert-ref-v1"
DETECTOR_SCHEMA_VERSION = "trailsight-detector-schema-v1"

SNAPSHOT_STATUSES = ("PENDING", "RUNNING", "COMPLETE", "FAILED")
REVIEW_BANDS = ("HIGH", "MEDIUM", "LOW", "UNSCORED")
UNSCORED_REASONS = (
    "NOT_YET_OBSERVED",
    "NO_FIRST_ORDER_CONTEXT",
    "NO_SECOND_ORDER_CONTEXT",
    "NON_FINITE_SCORE",
)
ALERT_REASON_CODE = "ENTERED_HIGH"
ALERT_CREATED_STATE = "NOT_REVIEWED"

DEFAULT_WORKERS = 1
MAX_FINAL_SNAPSHOT_SECONDS = 30 * 60
MAX_PHYSICAL_RAM_FRACTION = 0.70
