"""Structured model output and HTTP-facing AI response contracts."""

from __future__ import annotations

from enum import Enum
import re

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from trailsight_v2.domain.models import DisplayEvidenceV2, InvestigationContextV2, SubjectType


_DISPLAY_LABEL = re.compile(r"\[E[1-9][0-9]*\]", re.IGNORECASE)


class AIModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class FindingCategory(str, Enum):
    DETECTOR_OUTPUT = "DETECTOR_OUTPUT"
    OBSERVED_FACT = "OBSERVED_FACT"
    INTERPRETATION = "INTERPRETATION"


class InvestigationStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    UNAVAILABLE = "UNAVAILABLE"


class FindingV2(AIModel):
    category: FindingCategory
    text: str
    evidence_ids: list[str] = Field(min_length=1)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        text = value.strip()
        if not text:
            raise ValueError("finding text must be non-empty")
        if _DISPLAY_LABEL.search(text):
            raise ValueError("display evidence labels must not be generated by the model")
        return text

    @field_validator("evidence_ids")
    @classmethod
    def validate_evidence_ids(cls, values: list[str]) -> list[str]:
        normalized = [value.strip() for value in values]
        if any(not value for value in normalized):
            raise ValueError("evidence IDs must be non-empty")
        if len(normalized) != len(set(normalized)):
            raise ValueError("finding evidence IDs must be unique")
        return normalized


class InvestigationOutputV2(AIModel):
    status: InvestigationStatus
    findings: list[FindingV2] = Field(max_length=5)
    limits: list[str] = Field(max_length=3)

    @field_validator("limits")
    @classmethod
    def validate_limits(cls, values: list[str]) -> list[str]:
        normalized = [value.strip() for value in values]
        if any(not value for value in normalized):
            raise ValueError("limits must be non-empty")
        return normalized

    @model_validator(mode="after")
    def validate_shape(self) -> "InvestigationOutputV2":
        if self.status is InvestigationStatus.UNAVAILABLE:
            if self.findings:
                raise ValueError("UNAVAILABLE output must contain no findings")
            if not self.limits:
                raise ValueError("UNAVAILABLE output must explain at least one limit")
        if self.status is InvestigationStatus.PARTIAL:
            if not self.findings or not self.limits:
                raise ValueError("PARTIAL output requires findings and limits")
        return self


class DisplayEvidenceItemV2(AIModel):
    label: str
    evidence: DisplayEvidenceV2


class InvestigationResponseV2(AIModel):
    investigation_id: str
    run_status: InvestigationStatus
    subject_type: SubjectType
    subject_ref: str
    context: InvestigationContextV2
    findings: tuple[FindingV2, ...]
    limits: tuple[str, ...]
    display_evidence: tuple[DisplayEvidenceItemV2, ...]


class CreateInvestigationRequestV2(AIModel):
    subject_type: SubjectType
    subject_ref: str = Field(min_length=1)
    origin_alert_ref: str | None = Field(default=None, min_length=1)
    origin_transaction_ref: str | None = Field(default=None, min_length=1)


class FollowUpRequestV2(AIModel):
    question: str = Field(min_length=1, max_length=500)

    @field_validator("question")
    @classmethod
    def strip_question(cls, value: str) -> str:
        question = value.strip()
        if not question:
            raise ValueError("follow-up question must be non-empty")
        return question


def validate_output_for_mode(
    output: InvestigationOutputV2,
    *,
    mode: str,
) -> InvestigationOutputV2:
    count = len(output.findings)
    if output.status is InvestigationStatus.SUCCESS:
        minimum, maximum = (2, 5) if mode == "initial" else (1, 3)
        if not minimum <= count <= maximum:
            raise ValueError(
                f"{mode} SUCCESS output requires {minimum} to {maximum} findings"
            )
    elif output.status is InvestigationStatus.PARTIAL:
        maximum = 5 if mode == "initial" else 3
        if not 1 <= count <= maximum:
            raise ValueError(f"{mode} PARTIAL output requires 1 to {maximum} findings")
    return output
