import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { getAccountDetail, getAccountTransactions } from "../api/client";
import type { AccountDetailResponse, ApplicationError, CursorPage, EvidenceDisplay, SupportingTransactionRow } from "../api/types";
import { AIInvestigation } from "../components/AIInvestigation";
import { TransactionsTable } from "../components/tables";
import { AccountBankCountryConnectionsMap, AccountRelationshipGraph, ActivityTimeline, CompactBars } from "../components/visualizations";
import { AccountIdentityText, BankCountry, CursorPagination, DetectorCutoff, EmptyState, InlineError, LoadingState, NetworkReviewBand, PageHeader, ReviewWorkflowStatus, Section, formatMoney, formatUtc } from "../components/ui";
import type { EvidenceFocus } from "../lib/evidence";

export function AccountDetailPage() {
  const { accountRef = "" } = useParams(); const [params] = useSearchParams(); const navigate = useNavigate();
  const originAlert = params.get("origin_alert_ref"); const originTransaction = params.get("origin_transaction_ref");
  const [detail, setDetail] = useState<AccountDetailResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [focus, setFocus] = useState<EvidenceFocus | null>(null); const [focusedEvidence, setFocusedEvidence] = useState<EvidenceDisplay | null>(null);
  const [transactionPage, setTransactionPage] = useState<CursorPage<SupportingTransactionRow> | null>(null); const [transactionCursor, setTransactionCursor] = useState<string | null>(null); const [transactionLoading, setTransactionLoading] = useState(false); const [transactionError, setTransactionError] = useState<string | null>(null); const transactionCursorStack = useRef<Array<string | null>>([]);
  const originKey = `${originAlert ?? ""}|${originTransaction ?? ""}`;
  useEffect(() => { let active = true; setDetail(null); setTransactionPage(null); setTransactionCursor(null); transactionCursorStack.current = []; setTransactionError(null); setFocus(null); setFocusedEvidence(null); setError(null); if (originAlert && originTransaction) { setLoading(false); setError("Invalid historical context: an account route may preserve either origin_alert_ref or origin_transaction_ref, never both."); return () => { active = false; }; } setLoading(true); getAccountDetail(accountRef, { origin_alert_ref: originAlert, origin_transaction_ref: originTransaction }).then((result) => { if (active) { setDetail(result); setTransactionPage(result.transactions); } }).catch((caught: ApplicationError) => { if (active) setError(caught.message ?? "Account detail could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [accountRef, originKey]);
  const loadTransactionPage = useCallback(async (cursor: string | null) => { setTransactionLoading(true); setTransactionError(null); try { const result = await getAccountTransactions(accountRef, { origin_alert_ref: originAlert, origin_transaction_ref: originTransaction, cursor, limit: 50, direction: "BOTH" }); setTransactionPage(result); setTransactionCursor(cursor); return true; } catch (caught) { const failure = caught as ApplicationError; setTransactionError(failure.message ?? "Account transactions could not be loaded."); return false; } finally { setTransactionLoading(false); } }, [accountRef, originKey]);
  const onEvidenceFocus = useCallback((next: EvidenceFocus | null, evidence: EvidenceDisplay | null) => { setFocus(next); setFocusedEvidence(evidence); }, []);
  const nodeByRef = useMemo(() => new Map(detail?.account_network.counterparties.map((node) => [node.account_ref, node]) ?? []), [detail]);
  const historicalLabel = detail?.context.origin_alert_ref ? `Historical context from Alert ${detail.context.origin_alert_ref}` : detail?.context.origin_transaction_ref ? `Historical context from Transaction ${shortRef(detail.context.origin_transaction_ref)}` : undefined;
  if (loading) return <LoadingState label={`Loading account ${accountRef}…`} />; if (error || !detail) return <InlineError message={error ?? "Account detail is unavailable."} />; const { account_identity: account } = detail;
  return <>
    <PageHeader title="Account Investigation" purpose="Canonical Bank + Account review context, bounded relationships, deterministic activity, alert history, and grounded AI assistance." meta={<code className="page-ref">{account.account_ref}</code>} />
    <Section id="account-review" focused={focus?.uiTarget === "account-review"} title="1. Account Identity + Network Review" description="The detector band prioritizes review. It is not laundering probability or an AML disposition."><div className="account-identity-strip"><div><span className="eyebrow">Canonical account</span><AccountIdentityText value={account} /><code>{account.account_ref}</code></div><div><span className="eyebrow">Bank Country</span><BankCountry value={account.bank_country} /></div><div><span className="eyebrow">Network Review Band</span><NetworkReviewBand value={detail.network_review_state.network_review_band} /></div><DetectorCutoff value={detail.context.detector_cutoff} historicalLabel={historicalLabel} /></div><p className="structural-explanation">{detail.context.origin_alert_ref || detail.context.origin_transaction_ref ? "Historical detector state returned for the resolved origin context. The band is review prioritization, not an AML verdict." : "Latest completed detector state returned by the backend. The band is review prioritization, not an AML verdict."}</p><DetectorDetailsDisclosure detail={detail} /></Section>
    <Section title="2. Observed Activity" description="Bounded counts returned for the resolved investigation context."><div className="metric-grid"><Metric label="Incoming transactions" value={detail.observed_activity.incoming_count} /><Metric label="Outgoing transactions" value={detail.observed_activity.outgoing_count} /><Metric label="Distinct counterparties" value={detail.observed_activity.distinct_counterparties} /><Metric label="Outgoing counterparties" value={detail.observed_activity.outgoing_distinct_counterparties} /></div></Section>
    <Section id="account-network" focused={focus?.uiTarget === "account-network"} title="3. Account Network" description="One-hop canonical relationships only; payload bounds and truncation come from the backend."><AccountRelationshipGraph network={detail.account_network} /></Section>
    <Section id="counterparty-table" focused={focus?.uiTarget === "counterparty-table"} title="4. Transactions / Counterparties" description="Concrete bounded records at the selected context."><div className="account-table-stack"><div><h3>Transactions</h3>{transactionError && <InlineError message={transactionError} />}{transactionPage?.items.length === 0 ? <EmptyState title="No transactions in this bounded context." /> : <TransactionsTable dense items={transactionPage?.items ?? detail.transactions.items} onOpen={(item) => navigate(`/transactions/${encodeURIComponent(item.transaction_ref)}`)} />}{transactionPage && <CursorPagination loading={transactionLoading} hasNext={transactionPage.has_more} hasPrevious={transactionCursorStack.current.length > 0} onNext={async () => { if (!transactionPage.next_cursor) return; const previousCursor = transactionCursor; if (await loadTransactionPage(transactionPage.next_cursor)) transactionCursorStack.current.push(previousCursor); }} onPrevious={async () => { if (transactionCursorStack.current.length === 0) return; const previousCursor = transactionCursorStack.current[transactionCursorStack.current.length - 1]; if (await loadTransactionPage(previousCursor)) transactionCursorStack.current.pop(); }} />}</div><div><h3>Direct counterparties</h3><div className="table-scroll"><table className="data-table data-table--dense"><thead><tr><th>Counterparty</th><th>In</th><th>Out</th><th>Total</th></tr></thead><tbody>{detail.counterparties.map((relationship) => { const node = nodeByRef.get(relationship.counterparty_account_ref); return <tr key={relationship.counterparty_account_ref}><td>{node ? <div className="identity-stack"><AccountIdentityText value={node} /><BankCountry value={node.bank_country} compact /></div> : <code>{relationship.counterparty_account_ref}</code>}</td><td>{relationship.incoming_count}</td><td>{relationship.outgoing_count}</td><td>{relationship.total_count}</td></tr>; })}</tbody></table></div></div></div></Section>
    <Section id="activity-context" focused={focus?.uiTarget === "activity-context"} title="5. Activity Over Time" description="Time-series amounts remain currency-separated and counts use a separate axis."><ActivityTimeline activity={detail.activity_over_time} /></Section>
    <Section id="currency-activity" focused={focus?.uiTarget === "currency-activity"} title="6. Currency Activity" description="No aggregation across unlike currencies."><div className="split-8-4"><CompactBars ariaLabel="Currency activity transaction counts, separated by currency" rows={detail.currency_activity.map((row) => ({ label: row.currency, incoming: row.incoming_count, outgoing: row.outgoing_count }))} /><div className="currency-list">{detail.currency_activity.map((row) => <div key={row.currency}><strong>{row.currency}</strong><span>Incoming {formatMoney(row.incoming_amount, row.currency)}</span><span>Outgoing {formatMoney(row.outgoing_amount, row.currency)}</span></div>)}</div></div></Section>
    <Section id="bank-country-route" focused={focus?.uiTarget === "bank-country-route"} title="7. Bank-Country Flows" description="Deterministic synthetic bank metadata; never customer geography."><AccountBankCountryConnectionsMap rootBankCountry={account.bank_country} flows={detail.bank_country_flows} /><div className="bank-country-flow-table"><h3>Deterministic Bank-Country flow summary</h3><div className="table-scroll"><table className="data-table data-table--dense"><thead><tr><th>Bank Country</th><th>Incoming Txns</th><th>Outgoing Txns</th><th>Counterparties</th><th>Latest interaction</th></tr></thead><tbody>{detail.bank_country_flows.map((row) => <tr key={row.bank_country}><td><BankCountry value={row.bank_country} /></td><td>{row.incoming_transaction_count}</td><td>{row.outgoing_transaction_count}</td><td>{row.distinct_counterparties}</td><td><code>{formatUtc(row.latest_interaction)}</code></td></tr>)}</tbody></table></div></div></Section>
    <Section id="alert-history" focused={focus?.uiTarget === "alert-history"} title="8. Alert History" description="Network Pattern Alert history and human review progress are distinct from immutable detector outputs."><div className="table-scroll"><table className="data-table data-table--dense"><thead><tr><th>Alert Ref</th><th>Entry cutoff</th><th>Reason</th><th>Review status</th></tr></thead><tbody>{detail.alert_history.map((alert) => <tr key={alert.alert_ref}><td><code>{alert.alert_ref}</code></td><td><code>{formatUtc(alert.entry_cutoff)}</code></td><td>{alert.primary_reason.replace(/_/g, " ")}</td><td><ReviewWorkflowStatus value={alert.review_status} /></td></tr>)}</tbody></table></div></Section>
    <Section title="9. AI Investigation" description="Grounded AI assistance remains bounded to this account and its resolved historical context.">{focusedEvidence && <div className="focused-evidence-strip"><span className="evidence-marker">{focusedEvidence.label ? `Evidence ${focusedEvidence.label}` : "Resolved evidence"}</span><span>{focusedEvidence.evidence_type}</span><code>{focusedEvidence.evidence_id}</code></div>}<AIInvestigation subject_type="ACCOUNT" subject_ref={account.account_ref} origin_alert_ref={detail.context.origin_alert_ref} origin_transaction_ref={detail.context.origin_transaction_ref} onEvidenceFocus={onEvidenceFocus} /></Section>
  </>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="metric"><span>{label}</span><strong>{new Intl.NumberFormat("en-CA").format(value)}</strong></div>; }
function shortRef(value: string) { return value.length > 24 ? `${value.slice(0, 12)}…${value.slice(-8)}` : value; }
function DetectorDetailsDisclosure({ detail }: { detail: AccountDetailResponse }) { const state = detail.network_review_state; const support = detail.detector_support; return <details className="detector-details"><summary>Detector technical details</summary><dl><div><dt>Scoring eligible</dt><dd>{state.scoring_eligible ? "Yes" : "No"}</dd></div><div><dt>Unscored reason</dt><dd>{state.unscored_reason ?? "Not applicable"}</dd></div><div><dt>Score</dt><dd>{state.network_pattern_score ?? "Not scored"}</dd></div><div><dt>Rank</dt><dd>{state.rank ?? "Not scored"}</dd></div><div><dt>Percentile</dt><dd>{state.percentile ?? "Not scored"}</dd></div><div><dt>First-order neighbors</dt><dd>{support?.first_order_neighbor_count ?? "Not available"}</dd></div><div><dt>Second-order neighbors</dt><dd>{support?.second_order_neighbor_count ?? "Not available"}</dd></div><div><dt>Block measures</dt><dd>{support ? [support.block_measure_1, support.block_measure_2, support.block_measure_3].map((value) => value ?? "n/a").join(" / ") : "Not available"}</dd></div><div><dt>Snapshot</dt><dd><code>{detail.context.snapshot_id}</code></dd></div></dl><p>Technical values are backend-returned detector outputs for review context, not laundering probability.</p></details>; }
