import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getTransactionDetail } from "../api/client";
import { buildAccountDetailHref, buildTransactionDetailHref } from "../api/query";
import type { ApplicationError, EvidenceDisplay, TransactionDetailResponse } from "../api/types";
import { AIInvestigation } from "../components/AIInvestigation";
import { AccountLink } from "../components/links";
import { TransactionsTable } from "../components/tables";
import { AccountRelationshipGraph, ActivityTimeline, BankCountryRouteMap } from "../components/visualizations";
import { BankCountry, DetectorCutoff, InlineError, LoadingState, NetworkReviewBand, PageHeader, ReviewPriority, Section, formatMoney, formatUtc } from "../components/ui";
import type { EvidenceFocus } from "../lib/evidence";

export function TransactionDetailPage() {
  const { transactionRef = "" } = useParams(); const navigate = useNavigate();
  const [detail, setDetail] = useState<TransactionDetailResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [networkSide, setNetworkSide] = useState<"sender" | "receiver">("sender"); const [focus, setFocus] = useState<EvidenceFocus | null>(null); const [focusedEvidence, setFocusedEvidence] = useState<EvidenceDisplay | null>(null);
  useEffect(() => { let active = true; setDetail(null); // route ref change clears stale subject state
    setFocus(null); setFocusedEvidence(null); setNetworkSide("sender"); setLoading(true); setError(null);
    getTransactionDetail(transactionRef).then((result) => { if (active) setDetail(result); }).catch((caught: ApplicationError) => { if (active) setError(caught.message ?? "Transaction detail could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [transactionRef]);
  const onEvidenceFocus = useCallback((next: EvidenceFocus | null, evidence: EvidenceDisplay | null) => { setFocus(next); setFocusedEvidence(evidence); }, []);
  const supportingRows = useMemo(() => [...new Map((detail?.supporting_evidence_summary.flatMap((item) => item.supporting_transactions) ?? []).map((row) => [row.transaction_ref, row])).values()], [detail]);
  const focusedRefs = useMemo(() => new Set(focus?.supportingTransactionRefs ?? []), [focus]);
  if (loading) return <LoadingState label={`Loading transaction ${transactionRef}…`} />; if (error || !detail) return <InlineError message={error ?? "Transaction detail is unavailable."} />;
  const facts = detail.transaction_facts; const selectedNetwork = detail.local_network_summary[networkSide];
  const senderHref = buildAccountDetailHref(facts.sender.account_ref, { origin_transaction_ref: facts.transaction_ref });
  const receiverHref = buildAccountDetailHref(facts.receiver.account_ref, { origin_transaction_ref: facts.transaction_ref });
  return <>
    <PageHeader title="Transaction Investigation" purpose="Point-in-time transfer facts, endpoint context, and bounded supporting evidence." meta={<code className="page-ref">{facts.transaction_ref}</code>} />
    <Section id="review-priority" focused={focus?.uiTarget === "review-priority"} title="AML Review Priority" description="Priority derived from endpoint account bands at the applicable detector snapshot."><div className="priority-summary"><div className="priority-summary__label"><span className="eyebrow">AML Review Priority</span><ReviewPriority value={detail.review_state.aml_review_priority} /></div><div><span className="eyebrow">Derivation</span><p>{detail.review_state.derivation_text}</p></div><div className="endpoint-bands"><span><small>Sender band</small><NetworkReviewBand value={detail.review_state.sender_band} /></span><span><small>Receiver band</small><NetworkReviewBand value={detail.review_state.receiver_band} /></span></div><DetectorCutoff value={detail.review_state.detector_cutoff} /></div></Section>
    <Section title="AI Assessment" className="section--ai"><AIInvestigation subject_type="TRANSACTION" subject_ref={facts.transaction_ref} origin_alert_ref={null} origin_transaction_ref={null} onEvidenceFocus={onEvidenceFocus} /></Section>
    <Section id="bank-country-route" focused={focus?.uiTarget === "bank-country-route"} title="Transaction Summary + Bank-Country Route" description="Bank Country describes deterministic synthetic Bank metadata only."><div className="summary-map-grid"><div className="transaction-summary"><div><span>Amount paid</span><strong>{formatMoney(facts.amount_paid, facts.payment_currency)}</strong></div><div><span>Amount received</span><strong>{formatMoney(facts.amount_received, facts.receiving_currency)}</strong></div><div><span>Payment format</span><strong>{facts.payment_format}</strong></div><div><span>Sender</span><AccountLink value={facts.sender} to={senderHref} /><BankCountry value={facts.sender.bank_country} /></div><div><span>Receiver</span><AccountLink value={facts.receiver} to={receiverHref} /><BankCountry value={facts.receiver.bank_country} /></div></div><BankCountryRouteMap route={detail.bank_country_route} /></div></Section>
    <Section id="transaction-facts" focused={focus?.uiTarget === "transaction-facts"} title="Transaction Facts" description="Exact deterministic fields for the selected transaction."><dl className="fact-grid"><Fact label="Transaction Ref" value={facts.transaction_ref} mono /><Fact label="Timestamp" value={formatUtc(facts.timestamp)} mono /><Fact label="Sender" value={<AccountLink value={facts.sender} to={senderHref} />} /><Fact label="Receiver" value={<AccountLink value={facts.receiver} to={receiverHref} />} /><Fact label="Amount paid" value={formatMoney(facts.amount_paid, facts.payment_currency)} /><Fact label="Amount received" value={formatMoney(facts.amount_received, facts.receiving_currency)} /><Fact label="Payment format" value={facts.payment_format} /><Fact label="Currency route" value={facts.currency_pair} /></dl></Section>
    <Section title="Sender and Receiver Accounts" description="Endpoint account state at the transaction’s applicable historical cutoff."><div className="endpoint-card-grid"><EndpointCard id="sender-account" focused={focus?.uiTarget === "sender-account"} title="Sender account" card={detail.sender_account_card} href={senderHref} /><EndpointCard id="receiver-account" focused={focus?.uiTarget === "receiver-account"} title="Receiver account" card={detail.receiver_account_card} href={receiverHref} /></div></Section>
    <Section id="investigation-indicators" focused={focus?.uiTarget === "investigation-indicators"} title="Deterministic Investigation Indicators" description="Observed facts in the resolved transaction context."><div className="indicator-grid">{detail.investigation_indicators.map((indicator) => <article key={indicator.key} className={focus?.evidenceId === indicator.evidence_id ? "indicator evidence-focused" : "indicator"}><span className="eyebrow">Observed</span><h3>{indicator.title}</h3><strong>{indicator.observed_text}</strong><p>{indicator.detail}</p></article>)}</div></Section>
    <Section id="activity-context" focused={focus?.uiTarget === "activity-context"} title="Sender Activity — Prior 30 Days" description="Sender-rooted amounts by currency, with transaction counts separately encoded."><ActivityTimeline activity={detail.activity_context} /></Section>
    <Section id="account-network" focused={focus?.uiTarget === "account-network"} title="Local Account Network" description="Backend-bounded one-hop relationship context." actions={<div className="segmented" role="group" aria-label="Network subject"><button className={networkSide === "sender" ? "is-active" : ""} onClick={() => setNetworkSide("sender")}>Sender</button><button className={networkSide === "receiver" ? "is-active" : ""} onClick={() => setNetworkSide("receiver")}>Receiver</button></div>}>{selectedNetwork ? <AccountRelationshipGraph network={selectedNetwork} /> : <div className="state">No one-hop relationship payload is available for this endpoint.</div>}</Section>
    <Section id="supporting-evidence" focused={focus?.uiTarget === "supporting-evidence"} title="Supporting Transactions / Evidence" description="Bounded deterministic records supporting the investigation.">{focusedEvidence && <div className="focused-evidence-strip"><span className="evidence-marker">{focusedEvidence.label ? `Evidence ${focusedEvidence.label}` : "Resolved evidence"}</span><span>{focusedEvidence.evidence_type}</span><code>{focusedEvidence.evidence_id}</code></div>}<div className="evidence-table-wrap"><table className="data-table data-table--dense evidence-table"><thead><tr><th>Label</th><th>Evidence Type</th><th>UI Target</th><th>Context</th><th>Supporting Txns</th></tr></thead><tbody>{detail.supporting_evidence_summary.map((item) => <tr key={item.evidence_id} className={focus?.evidenceId === item.evidence_id ? "evidence-row-focused" : ""}><td><span className="evidence-marker">{item.label}</span></td><td><code>{item.evidence_type}</code></td><td>{item.ui_target}</td><td><code>{formatUtc(item.context_time)}</code></td><td className="numeric">{item.supporting_transaction_count}{item.support_truncated ? "+" : ""}</td></tr>)}</tbody></table></div>{!!supportingRows.length && <div className="supporting-transactions"><h3>Bounded supporting transaction rows</h3><TransactionsTable items={supportingRows} dense focusedRefs={focusedRefs} onOpen={(item) => navigate(buildTransactionDetailHref(item.transaction_ref))} /></div>}</Section>
  </>;
}
function Fact({ label, value, mono = false }: { label: string; value: ReactNode; mono?: boolean }) { return <div><dt>{label}</dt><dd className={mono ? "mono" : ""}>{value}</dd></div>; }
function EndpointCard({ id, title, card, href, focused }: { id: string; title: string; card: TransactionDetailResponse["sender_account_card"]; href: string; focused: boolean }) { return <article id={id} tabIndex={focused ? -1 : undefined} className={focused ? "endpoint-card evidence-focused" : "endpoint-card"}><span className="eyebrow">{title}</span><AccountLink value={card.account} to={href} /><BankCountry value={card.account.bank_country} /><div><small>Network Review Band</small><NetworkReviewBand value={card.network_review_band} /></div><p>{card.observed_summary}</p><DetectorCutoff value={card.detector_cutoff} /><Link className="button button--secondary button-link" to={href}>View Account</Link></article>; }
